export const DATA_SOURCE = 'DATA_SOURCE';
export const POSTINGS_REPOSITORY = 'POSTINGS_REPOSITORY';
export const LIKEDS_REPOSITORY = 'LIKEDS_REPOSITORY';
export const REPORTS_REPOSITORY = 'REPORTS_REPOSITORY';
